version: '2'
services:
  redis:
    hostname: redis
    container_name: redis
    image: makeomatic/redis-cluster:3.2.8

  rabbitmq:
    image: makeomatic/rabbitmq:3.6.9
    container_name: rabbitmq
    hostname: rabbitmq

  ms-files:
    image: makeomatic/ms-files
    container_name: ms-files
    hostname: ms-files
    volumes:
      - ./configs:/configs:ro
    environment:
      NCONF_FILE_PATH: '["/configs/amqp.js","/configs/redis.js","/configs/files.js"]'
      NODE_ENV: production

  tester:
    container_name: tester
    image: makeomatic/node:8.1.3-tex-tester
    links:
      - redis
      - rabbitmq
    working_dir: /src
    ports:
      - "9229:9229"
    volumes:
      - ${PWD}:/src
    environment:
      NODE_ENV: "test"
      DEBUG: ${DEBUG}
      NCONF_NAMESPACE: MS_LATEX
      DOTENV_FILE_PATH: "/src/__tests__/.env"
    command: tail -f /dev/null
