version: '3'

services:
  ms-files:
    image: makeomatic/ms-files:12.18
    depends_on:
      - redis-cluster
      - rabbitmq
    volumes:
      - ${PWD}/__tests__/configs:/configs:ro
      - ${PWD}/__tests__/.env:/src/.env:ro
    environment:
      NCONF_FILE_PATH: '["/configs/amqp.js","/configs/redis.js","/configs/files.js"]'
      NODE_ENV: production

  tester:
    ports:
      - "9229:9229"
      - "9222:9222"
    cap_add:
      - SYS_ADMIN
    user: node
    environment:
      NODE_ENV: "test"
      DEBUG: ${DEBUG}
      DOTENV_FILE_PATH: "/src/__tests__/.env"
      CHROME_PATH: /usr/bin/chromium-browser
    command: tail -f /dev/null
